# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.title = QtWidgets.QLabel(Form)
        self.title.setGeometry(QtCore.QRect(140, 10, 211, 29))
        font = QtGui.QFont()
        font.setFamily("Gill Sans Nova Light")
        font.setPointSize(13)
        self.title.setFont(font)
        self.title.setScaledContents(True)
        self.title.setObjectName("title")
        self.image_qrl = QtWidgets.QLabel(Form)
        self.image_qrl.setGeometry(QtCore.QRect(0, 10, 111, 101))
        self.image_qrl.setText("")
        self.image_qrl.setPixmap(QtGui.QPixmap("images/logocircle.png"))
        self.image_qrl.setScaledContents(True)
        self.image_qrl.setObjectName("image_qrl")
        self.body = QtWidgets.QLabel(Form)
        self.body.setGeometry(QtCore.QRect(110, 30, 261, 101))
        self.body.setScaledContents(True)
        self.body.setObjectName("body")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "About"))
        self.title.setText(_translate("Form", "QRL Light Wallet V0.0.1"))
        self.body.setText(_translate("Form", "<html><head/><body><p align=\"center\">QRL Light Wallet it\'s focus is on:</p><p align=\"center\">speed, performance and minimalism.</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
